version: '3.7'

services:

  consul-server:
    image: hashicorp/consul:1.11.2
    container_name: consul-server
    restart: always
    volumes:
      - ./consul/server.json:/consul/config/server.json:ro
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=1"

  consul-client:
    image: hashicorp/consul:1.11.2
    container_name: consul-client
    restart: always
    volumes:
      - ./consul/client.json:/consul/config/client.json:ro
    command: "agent"
    depends_on:
      - consul-server

  postgres:
    image: postgres
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'

  movie-battle:
    image: movie-battle:1.0.0-SNAPSHOT
    container_name: movie-battle
    restart: always
    environment:
      SPRING_APPLICATION_NAME: 'movie-battle'
      SPRING_PROFILES_ACTIVE: 'prd'
      SPRING_CONFIG_IMPORT: 'consul:localhost:8500'
      SPRING_CLOUD_CONSUL_CONFIG_ENABLED: 'true'
      SPRING_CLOUD_CONSUL_CONFIG-FAIL: 'true'
      SPRING_CLOUD_CONSUL_FORMAT: 'files'
      SPRING_CLOUD_CONSUL_CONFIG_PREFIX: 'movie-battle'
      LOGGING_LEVEL_ROOT: 'DEBUG'
    ports:
      - '8080:8080'
    depends_on:
      - postgres
      - consul-client
