version: '3.7'

services:

  consul-server:
    image: hashicorp/consul:1.11.2
    container_name: consul-server
    restart: always
    volumes:
      - ./consul/server.json:/consul/config/server.json:ro
    ports:
      - "8500:8500"
      - "8600:8600/tcp"
      - "8600:8600/udp"
    command: "agent -bootstrap-expect=1"

  consul-client:
    image: hashicorp/consul:1.11.2
    container_name: consul-client
    restart: always
    volumes:
      - ./consul/client.json:/consul/config/client.json:ro
    command: "agent"
    depends_on:
      - consul-server

  postgres:
    image: postgres
    container_name: postgres
    hostname: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
  
  redis:
    image: redis
    container_name: redis
    restart: always
    ports:
      - '6379:6379'
    command: redis-server

  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=sns,sqs
      - AWS_DEFAULT_REGION=sa-east-1
      - AWS_ACCESS_KEY_ID=aws_access_key
      - AWS_SECRET_ACCESS_KEY=aws_secret_key
      - DEFAULT_REGION=sa-east-1
      - http_proxy=
      - https_proxy=
    